version: '2'

services:
  app:
    image: 'survey-maker:latest'
    build:
      context: .
    container_name: 'survey-maker'
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5500/SurveyMaker
      SPRING_DATASOURCE_USERNAME: survey-admin
      SPRING_DATASOURCE_PASSWORD: secret-admin-password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  database:
    image: 'postgres:13.1-alpine'
    container_name: 'survey-maker-postgres'
    environment:
      POSTGRES_USER: survey-admin
      POSTGRES_PASSWORD: secret-admin-password
      POSTGRES_DB: SurveyMaker
    volumes:
      - ./db-data/:/var/lib/postgres/data
    ports:
      - "5500:5432"
    restart: on-failure